[common]
default_envs = rev_8
platform = espressif32@7.0.1
framework = arduino

[platformio]
boards_dir = boards




; ------------------------------------------
; MICRO JOURNAL REVISION 8
; ST7306 300x400 reflective LCD
; YDP420H001-V3
; ------------------------------------------
[env:rev_8]
extends = common
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = dio_opi
board_build.arduino_psram = enabled
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_upload.maximum_size = 4128768
board_build.filesystem = fatfs
board_build.partitions = partition_esp32s3_rev8_16mb.csv
upload_speed =  921600
monitor_speed = 115200
monitor_filters =
	default
	esp32_exception_decoder

lib_deps =
  ArduinoJson
  https://github.com/adafruit/Adafruit_Keypad
  https://github.com/h2zero/NimBLE-Arduino.git

build_src_filter =
  -<*>
  +<main.cpp>
  +<app/*>
  ;
  +<display/display.*>
  +<display/RLCD/*>
  ;
  +<keyboard/keyboard.*>
  +<keyboard/Keypad/Keypad.*>
  +<keyboard/Keypad/68/*>
  +<keyboard/Locale/*>
  ;
  +<service/Tools/*>
  +<service/Editor/*>
  +<service/Clock/*>
  +<service/Bidi/*>
  +<service/Updater/*>
  +<service/WifiEntry/*>
  +<service/Buffer/*>
  +<service/Sync/*>
  +<service/WordCounter/*>
  +<service/Send/*>
  +<service/MassStorage/*>

lib_ignore =
  FatFSUSB
  EPD
  EspUsbHost
  USBHIDBoot

build_flags =
  ;
  ;-D USE_SERIAL_KEYBOARD

  ; Configuration
  -D REV8
  -D KEYPAD_68
  -D BOARD_ESP32_S3
  -D USE_MSC ; mass storage
  -D USE_FAT
  -D FIRMWARE=\"/firmware_rev_8.bin\"

  ; DISPLAY
  -D PIN_SCLK=12
  -D PIN_MOSI=11
  -D PIN_CS=10
  -D PIN_DC=46
  -D PIN_RST=3

  ; ESP32 S3
  -D BOARD_HAS_PSRAM
  -DCONFIG_SPIRAM_CACHE_WORKAROUND
  -mfix-esp32-psram-cache-issue
  -mfix-esp32-psram-cache-strategy=memw
